osx_image: xcode8.3
sudo: required
dist: xenial
language: node_js
workspaces:
  use:
  - binaries
cache:
  directories:
  - node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"
addons:
before_install:
install:
- source ~/.bashrc
- npm install -g xvfb-maybe
- npm install
node_js:
- 10.15.3
jobs:
  include:
    - stage: Build binaries
      os: windows
      script:
      - npm run build
      - mkdir windows-binaries
      - mv -v build/flightgear-airports* windows-binaries/
      - ls -l windows-binaries
      workspaces:
        create:
          name: windows-binaries
          paths: windows-binaries
    - os: linux
      script:
      - npm run build
      - mkdir linux-binaries
      - mv -v build/flightgear-airports* linux-binaries/
      - ls -l linux-binaries
      workspaces:
        create:
          name: linux-binaries
          paths: linux-binaries
    - os: osx
      script:
      - npm run build
      - mkdir osx-binaries
      - mv -v build/flightgear-airports* osx-binaries/
      - ls -l osx-binaries
      workspaces:
        create:
          name: osx-binaries
          paths: osx-binaries
    - stage: Deploy
      install:
      - pwd
      - find -name *osx-binaries*
      - tar -xzf ${CASHER_DIR}/osx-binaries-fetch.tgz
      - find -name flightgear-airports*
      - cp ./Users/travis/build/Portree-Kid/flightgear-airports/osx-binaries/*.dmg build/
      - cp ./C:/Users/travis/build/Portree-Kid/flightgear-airports/windows-binaries/*.exe build/
      - cp ./linux-binaries/*.AppImage build/
      - ls -l "build/"
      script: skip
      workspaces:
        use:
        - windows-binaries
        - linux-binaries
        - osx-binaries
      deploy:
        skip_cleanup: true
        overwrite: true
        draft: true
        name: '0.0.33'
        provider: releases
        api_key:
          secure: FElxoWQZKIcc9gHFY4yp1CsqvJr76BWdDrp7VsgPN7PuEoZht5Boic3fWbxKyT1fKGr8Yem6CJBXQjaqIZiWWMxuF3KYmsdOK0YRpj6WCePpl0AdZcnWDMsAGuC3ornb1CB3R6x8fx7SMMl8Ghc9/JFDUdjduvT9A0KZ1JrTZLYpP1iOq+aAW0H3byu+tNfTDvee9MzMAtjKriDz0L5z94VQ1lEmuc79qUmNvv9gIJUoNOI58QCDUuOEz2eZPooMz5cOdaupzBK130V7ki/UWbP3meXmzRKN6/iSA9iXiIrBerFtA4wG6hVvKMvKP7d7NalWAtpzOElFivlo7tp+Z1SfjSfZHmZG/PMyndVh1VPmMzX6a76qLyJFGIvOZKOkzzmVyGSVGlUHm8GCkw5wd0S3m6f1eA/YJO5c8aduC7M+qZSuEVdzaAW5xf8Fb1/rs7jELZPxuzio9i+T7vRQ1OFrCBtExQAuO9EyfaIvaVQAImvhOPiza6zkfEkF622LIQZIBL9HZ1OeKKrdWaWG98nUGWDIFXb+B4IBM1cJIPRYmaAbnWVVCBzIGxcb1pMb/zzSocu9poEWCY/CVHuOG7Xg45pghTunPS54E9qxvBx8jDIGz4s3bRwWnBI0DJ5b6aBNqMpghmpKYMCoviT+RwCIKOENlFdrPWH5pk9CmRc=wYHBe6BJtqhkjodvabd6fSX5blecd/y9sSfHV9prk7PRFxkpkp4Fw/sp086SFlunTGmTn359T1mhgr0MD/VDRXu34PEdn47Jpu8CTPfnihiK/3iRaGqW0qLqhmpd6GYc1ecm9sahxYwXgWyCtGZQbdHvrCIiS/Zm1hQtg3Q0O3eYeF+zQXrfCCTIhLLy2egID4Z23RbK620y3dqcSfbWfLzPpXr+2MYVrNZ3gukKiVauf2kBYPNzMTKEtIBfAGHiwQwlCm/fRN5NcL9bwMGmMGktJkIHgpAa2A9nnyw7EadKEKqVw4tI/j1813/FDWlJZBg89RNsZJ0QGSMQcMB0h1XkWZFPV02gqMN2z2eNXsvTJ882g8UkCBzPWYsRQGNKEx9FUFtZO9HAjOnnpAsdTcaQYTow7BiVmPBePtCFKsPyqMgJUsuz6WhUmfJ5FMbMDKn1N6ymyBYmTic5KrT3FRR3s7vFyTNdfNfwd7aNMnZSGb2uHLZyGjrC2QFK3AE/F+jP2bMu/9rcuLcp/CSLpxpN5F6RpVVfqY8X9joEUeXOSd4kO7OPBsg4lxDCqzVmER/X+MEwM57cmyutTtaREZEDTKCoEhWtcMHqLpCojPWbMsKnMh7NRARNWETe76tcwO88K2LqQFvhhILeTXKlWDpNcbGwqSinF62RXG4DxUQ=
        file_glob: true    
        file: build/*
        on:
          branches: '0.0.33'
          repo: Portree-Kid/flightgear-airports
