osx_image: xcode8.3
sudo: required
dist: xenial
language: node_js
workspaces:
  use:
    - binaries
cache:
  directories:
  - node_modules
  - "$HOME/.electron"
  - "$HOME/.cache" 
addons: 
before_install: 
install:
- source ~/.bashrc
- npm install -g xvfb-maybe
- npm install
node_js:
- 10.15.3
jobs:
  include:
    - stage: Build binaries
      os: windows
      script:
        - npm run build
        - mkdir windows-binaries
        - mv -v build/flightgear-airports* windows-binaries/
        - ls -l windows-binaries
      workspaces:
        create:
          name: windows-binaries
          paths: windows-binaries
    - os: linux
      script:
        - npm run build
        - mkdir linux-binaries
        - mv -v build/flightgear-airports* linux-binaries/
        - ls -l linux-binaries
      workspaces:
        create:
          name: linux-binaries
          paths: linux-binaries
    - os: osx
      script:
        - npm run build
        - mkdir osx-binaries
        - mv -v build/flightgear-airports* osx-binaries/
        - ls -l osx-binaries
      workspaces:
        create:
          name: osx-binaries
          paths: osx-binaries
    - stage: Deploy
      install:
        - pwd 
        - tar -xzf ${CASHER_DIR}/osx-binaries-fetch.tgz
        - find -name flightgear-airports*
#        - find -name windows-binaries
#        - find -name osx-binaries
#        - find -name linux-binaries
#        - ls -l | grep "^d"
#        - ls -l "C:"
        - cp ./Users/travis/build/Portree-Kid/flightgear-airports/osx-binaries/*.dmg build/
        - cp ./C:/Users/travis/build/Portree-Kid/flightgear-airports/windows-binaries/*.exe build/
        - cp ./linux-binaries/*.AppImage build/
        - ls -l "build/"
      script: skip
      workspaces:
        use:
          - windows-binaries
          - linux-binaries
          - osx-binaries
      deploy:
        skip_cleanup: true
        overwrite: true
        draft: true
        name: '0.0.27'
        provider: releases
        api_key: 
          secure: gYevDrnBOPmUATTrkvryouwoH2R8yl3JpISN5U73UFZUXAl9wtTDQHK2gV0a2dLfZUFM/V8HAd9Tyy3SsfDbe8lPVvjVIPgEh48AVU2ip79NxGaUzD9L/VZyssLVVtec+v2t5ZaE8Ax5mJEs3Cvv6Mvja8dNOKo1oWp1qy5jvXY2hxhj3zsjcYhUDZVZeeAowFqITNNJS3xKCayGVLSd4VwASUmeNPo4dEfxV5gfJXddzUgE2CQWX+cPOrwsqlvMGrYIjJ6T9uXhbNnGFO5WxRGYbuZkNL0ShC2lT1z6grs7qVGHpoAIic2X5J+T2nSZ9iQoJy3jdpeOozD09AAO2OzawvhiDN5qK2w59u2ezzzkquH1T1kBzoUlTAzz2tQqAZJmMvQhwlmuFn5SVJproKNM7AVdUN+bF5PWznHPfv49BwiJ6NfHZujhZmp2u7wfRC+gSs9NxXawBpPOMR06Tq+e4OBxTE0XjlxpGQDWS8W+ADvW3d1a2plh4HWEq/FdhW8yj/3PuH13aVjuPXjpjQ0gR4+tUPdklcbY6vISKsxmOhODlIEdbMpuM/9Dd5Yn46VKOZM21rxoPiwy/m0jEwxtbH/rCk21/b0D7RjW5FWzZkZu3NJeQBO1VpjsYDh7A3JTqal/DMzOjx4z/UEfhVWdAEaHZUHBCyXgcebXb/M=
        file_glob: true    
        file: build/*
        on:
          branches: '0.0.27'
          repo: Portree-Kid/flightgear-airports
