osx_image: xcode8.3
sudo: required
dist: xenial
language: node_js
workspaces:
  use:
    - binaries
cache:
  directories:
  - node_modules
  - "$HOME/.electron"
  - "$HOME/.cache" 
addons: 
before_install: 
install:
- source ~/.bashrc
- npm install -g xvfb-maybe
- npm install
node_js:
- 10.15.3
jobs:
  include:
    - stage: Build binaries
      os: windows
      script:
        - npm run build
        - mkdir windows-binaries
        - mv -v build/flightgear-airports* windows-binaries/
        - ls -l windows-binaries
      workspaces:
        create:
          name: windows-binaries
          paths: windows-binaries
    - os: linux
      script:
        - npm run build
        - mkdir linux-binaries
        - mv -v build/flightgear-airports* linux-binaries/
        - ls -l linux-binaries
      workspaces:
        create:
          name: linux-binaries
          paths: linux-binaries
    - os: osx
      script:
        - npm run build
        - mkdir osx-binaries
        - mv -v build/flightgear-airports* osx-binaries/
        - ls -l osx-binaries
      workspaces:
        create:
          name: osx-binaries
          paths: osx-binaries
    - stage: Deploy
      install:
        - pwd 
        - tar -xzf ${CASHER_DIR}/osx-binaries-fetch.tgz
        - find -name flightgear-airports*
#        - find -name windows-binaries
#        - find -name osx-binaries
#        - find -name linux-binaries
#        - ls -l | grep "^d"
#        - ls -l "C:"
        - cp ./Users/travis/build/Portree-Kid/flightgear-airports/osx-binaries/*.dmg build/
        - cp ./C:/Users/travis/build/Portree-Kid/flightgear-airports/windows-binaries/*.exe build/
        - cp ./linux-binaries/*.AppImage build/
        - ls -l "build/"
      script: skip
      workspaces:
        use:
          - windows-binaries
          - linux-binaries
          - osx-binaries
      deploy:
        skip_cleanup: true
        overwrite: true
        draft: true
        name: '0.0.18'
        provider: releases
        api_key:
          secure: Xm3z86gQmpSajvlXSVgG7mxcaS5K7GfE4HrARIDR4pQ4UguQ3/fFOenRyKAQImmH0kLCSIbVE21NMAQ3YI2F9El9I6GU7Wirccsg14TZZiBQAzKOTXZ+JsBloeBxuTOsR84SkO6pV8OT/pRnQd9frqyc1W7wzoX+0sQykMztXCNfI+1MXXGOAgMzlKuDMO1PVENz0V63mWipL/Mae/SyrHa1Bws+4LJKvv42m0HMKdN7ekt41vxcSUvLmN+YLlqUEVr/eUhQXUNCaWlmM0KxmfuzTedca5/1yzLvN8smEt2I2b0DFRM3Mi/QdI22fVRHs6XGpm8yqZRKmhySDXFspXKWBiuCF6AezX6NiIe/ZUh10gIukjkyLtrNk/o29qhj2WE9HJz4xhsGMAx3632cLSMPku5ALN7jv5scWjwCGNHs4ZeZyyePMeGM6Y6pje1uJPbxWGjwoV6iI4Y4esP+z3KcXvZdnzkpYMy2mzdT4gf7A7zieax1YwB6U/MEanXYKFBH4yzYK9+hx3ck2eLT3LcV/ChHN2bKmERJdf18h+zI8e5YKTzd3/kHLiUUv19N2a4TUYloGOyzrLwn2VD1Xm4jJVVLTIQvWbH5YK7cNkHYa4+PnsB+JppSoby7HiBcothw4OLpJO8eCMqXcPRU1n+cRAZTB7VOS7pWh8e8LFE=
        file_glob: true    
        file: build/*
        on:
          branches: '0.0.18'
          repo: Portree-Kid/flightgear-airports
