osx_image: xcode8.3
sudo: required
dist: xenial
language: node_js
workspaces:
  use:
  - binaries
cache:
  directories:
  - node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"
addons:
before_install:
install:
- source ~/.bashrc
- npm install -g xvfb-maybe
- npm install
node_js:
- 10.15.3
jobs:
  include:
    - stage: Build binaries
      os: windows
      script:
      - npm run build
      - mkdir windows-binaries
      - mv -v build/flightgear-airports* windows-binaries/
      - ls -l windows-binaries
      workspaces:
        create:
          name: windows-binaries
          paths: windows-binaries
    - os: linux
      script:
      - npm run build
      - mkdir linux-binaries
      - mv -v build/flightgear-airports* linux-binaries/
      - ls -l linux-binaries
      workspaces:
        create:
          name: linux-binaries
          paths: linux-binaries
    - os: osx
      script:
      - npm run build
      - mkdir osx-binaries
      - mv -v build/flightgear-airports* osx-binaries/
      - ls -l osx-binaries
      workspaces:
        create:
          name: osx-binaries
          paths: osx-binaries
    - stage: Deploy
      install:
      - pwd
      - tar -xzf ${CASHER_DIR}/osx-binaries-fetch.tgz
      - find -name flightgear-airports*
      - cp ./Users/travis/build/Portree-Kid/flightgear-airports/osx-binaries/*.dmg build/
      - cp ./C:/Users/travis/build/Portree-Kid/flightgear-airports/windows-binaries/*.exe build/
      - cp ./linux-binaries/*.AppImage build/
      - ls -l "build/"
      script: skip
      workspaces:
        use:
        - windows-binaries
        - linux-binaries
        - osx-binaries
      deploy:
        skip_cleanup: true
        overwrite: true
        draft: true
        name: '0.0.27'
        provider: releases
        api_key:
          secure: C+xfU2GatGzATuyZfONg7YZM1eWfKRCWVnLM1J9kBwh0m4aDLNCIRkm5LpD2DZdauF4n1N5/5j3/56b/CigglDvjz2CgzBH8oqDelCbKCWneeARTOO5NjRPbjEAUnE+qNeVnfW3ia6nFvD6rHWScK3MFAd/JtzYICuHF577+OBmDpe7X6nGlsUC7PH8Sc+nSF70MGQFyRklEEEzbMzIdaHumO4Q+KBDY5Zv6tVSsW1otG6aPJMXVzX9hcx6fLpkJphDK19heZvfvRMu50jwSL+Q7r3bN8eVTTahwLGfgwZP5HyM3JCisc1zZ2xeCUsqs+kGHrN/t/8MDfW0uN0tRYfZJxL7HQK9A06ZK63gDG0vCqYEuRWlAixGk0BF1UZ7AQryO6N0HgTZkOOqqoZb4jVvoLo6ak6PXdCUaqStf0f8hHptgCYi4ehvcRiwmamBnUukcFzVfGNS22j5xSCFZ/KTPH/JSPAIV3W8EFxZ1vjChFmVXT22nB4IVd5eDRWov4Q458Tk3IaPlu5yX05pZ/6w1alT6N3cZVkJ/cGjlFoa8GKmEbdn/ptqQECFImiGgrizMjkp4tinK4yAfcw9aDtG8kWThmPw1i3haSBhZgjI+VAXh0+r3+GkLMeDgn7wrGIuzYA2EX61K/O6I3a6ybG83NGoLaPfNlPup3YUjuF8=
        file_glob: true
        file: build/*
        on:
          branches: '0.0.27'
          repo: Portree-Kid/flightgear-airports
